<?php

namespace IEEE\UserBundle\Repository;

/**
 * suggestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class suggestRepository extends \Doctrine\ORM\EntityRepository
{
}
