<?php

namespace IEEE\UserBundle\Repository;

/**
 * UserTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
